version: '3.8'

services:
#  redis:
#    image: redis:7.2.4
#    restart: always
#    ports:
#      - "${DB_PORT}:6379"
  consul:
    image: hashicorp/consul
    command: ["consul", "agent", "-dev", "-client", "0.0.0.0"]
    ports:
      - "8500:8500"