version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/resources:/var/www/resources
    depends_on:
      - go_app
    networks:
      - app_network

  consul:
    image: hashicorp/consul
    command: [ "consul", "agent", "-dev", "-client", "0.0.0.0" ]
    ports:
      - "8500:8500"
    networks:
      - app_network
    depends_on:
      - psql

  psql:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - app_network

  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
    deploy:
      replicas: 3
    ports:
      - "8080-8082:8080"
    depends_on:
      - psql
      - consul
      - redis
    networks:
      - app_network

  redis:
    image: "redis:7.2.4"
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    restart: always

    networks:
      - app_network
    volumes:
      - ./data/redis-data:/data


networks:
  app_network:
    driver: bridge
